/**
 * These (except dataEdit strings) should all be replaced by autogenerated model and html form in form_generated_mock.js.
 * This way they stay up to date when the XSL sheet changes!
 */

var dataEditStr1 =
    '<thedata id="something">' +
    '<meta>' +
    '<instanceID>7c990ed9-8aab-42ba-84f5-bf23277154ad</instanceID>' +
    '<timeStart/>' +
    '<timeEnd/>' +
    '</meta>' +
    '<nodeA>2012-02-05T15:34:00.000-04</nodeA>' +
    '<nodeB>b</nodeB>' +
    '<repeatGroup>' +
    '<nodeC>some data one</nodeC>' +
    '</repeatGroup>' +
    '<repeatGroup>' +
    '<nodeC></nodeC>' +
    '</repeatGroup>' +
    '<repeatGroup>' +
    '<nodeC></nodeC>' +
    '</repeatGroup>' +
    '<repeatGroup>' +
    '<nodeC></nodeC>' +
    '</repeatGroup>' +
    '<repeatGroup>' +
    '<nodeC>some data five</nodeC>' +
    '</repeatGroup>' +
    '<somenodes>' +
    '<A>two</A>' +
    '<B>three</B>' +
    '<C>four</C>' +
    '</somenodes>' +
    '<someweights>' +
    '<w1>1</w1>' +
    '<w2>3</w2>' +
    '<w.3>5</w.3>' +
    '</someweights>' +
    '</thedata>';

var dataStr2 =
    '<model>' +
    '<instance>' +
    '<random id="random"><formhub><uuid/></formhub>' +
    '<random__/>' +
    '<note_random/>' +
    '<uuid__/>' +
    '<note_uuid/>' +
    '<meta>' +
    '<instanceID/>' +
    '<timeStart/>' +
    '<timeEnd/>' +
    '</meta>' +
    '</random>' +
    '</instance>' +
    '</model>';

var formStr2 =
    '<form class="or" autocomplete="off" id="random">' +
    '<section class="form-logo"> </section>' +
    '<h2 id="form-title">Random<span></span></h2>' +
    '<label class="question">' +
    '<input name="/random/meta/instanceID" type="hidden" data-calculate="(1+1)" />' +
    '</label>' +
    '<fieldset class="trigger" name="/random/note_random">' +
    '<div class="question-icons"><span class="required"></span><span class="hint"></span></div>' +
    '<span lang="en" class="active">This is the random number that was generated: ' +
    '<span class="or-output" data-value="/random/random__"></span>' +
    '</span>' +
    '</fieldset>' +
    '<fieldset class="trigger" name="/random/note_uuid">' +
    '<div class="question-icons">' +
    '<span class="required"></span><span class="hint"></span>' +
    '</div>' +
    '<span lang="en" class="active">This is the uuid that was generated: ' +
    '<span class="or-output" data-value="/random/uuid__"></span>' +
    '</span>' +
    '</fieldset>' +
    '<fieldset id="or-calculated-items" style="display:none;">' +
    '<label class="question">' +
    '<input name="/random/formhub/uuid" type="hidden" data-calculate="uuid()" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/random/random__" type="hidden" data-calculate="random()" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/random/uuid__" type="hidden" data-calculate="uuid()" data-type-xml="string"/>' +
    '</label>' +
    '</fieldset>' +
    '</form>';

var dataStr3 =
    '<model>' +
    '<instance xmlns="http://www.w3.org/2002/xforms">' +
    '<random id="random"><formhub><uuid/></formhub>' +
    '<random__/>' +
    '<note_random/>' +
    '<uuid__/>' +
    '<note_uuid/>' +
    '<meta>' +
    '<instanceID>c13fe058-3349-4736-9645-8723d2806c8b</instanceID>' +
    '</meta>' +
    '</random>' +
    '</instance>' +
    '</model>';

var formStr3 =
    '<form class="or">' +
    '<section class="form-logo"> </section>' +
    '<h2 id="form-title">Random<span></span></h2>' +
    '<div id="stats" style="display: none;">' +
    '<span id="jrSelect">0</span><span id="jrSelect1">0</span>' +
    '<span id="jrItem">0</span><span id="jrInput">0</span>' +
    '<span id="jrItemset">0</span>' +
    '<span id="jrUpload">0</span><span id="jrTrigger">2</span>' +
    '<span id="jrRepeat">0</span><span id="jrRelevant">0</span>' +
    '<span id="jrConstraint">0</span><span id="jrCalculate">3</span>' +
    '<span id="jrPreload">1</span>' +
    '</div>' +
    '<fieldset id="or-preload-items" style="display:none;">' + /*****/
    '<label class="question">' +
    '<input name="/random/meta/instanceID" type="hidden" data-preload="instance" data-preload-params="id" data-type-xml="string" />' +
    '</label>' +
    '</fieldset>' + /*****/
    '<fieldset class="trigger ui-state-highlight" name="/random/note_random">' +
    '<div class="question-icons"><span class="required"></span><span class="hint"></span></div>' +
    '<span lang="en" class="active">This is the random number that was generated: ' +
    '<span class="or-output" data-value="/random/random__"></span>' +
    '</span>' +
    '</fieldset>' +
    '<fieldset class="trigger ui-state-highlight" name="/random/note_uuid">' +
    '<div class="question-icons">' +
    '<span class="required"></span><span class="hint"></span>' +
    '</div>' +
    '<span lang="en" class="active">This is the uuid that was generated: ' +
    '<span class="or-output" data-value="/random/uuid__"></span>' +
    '</span>' +
    '</fieldset>' +
    '<fieldset id="or-calculated-items" style="display:none;">' +
    '<label class="question">' +
    '<input name="/random/formhub/uuid" type="hidden" data-calculate="uuid()" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/random/random__" type="hidden" data-calculate="random()" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/random/uuid__" type="hidden" data-calculate="uuid()" data-type-xml="string"/>' +
    '</label>' +
    '</fieldset>' +
    '</form>';

var dataStr4 =
    '<model>' +
    '<instance>' +
    '<nodename_bug id=\"nodename_bug\"><formhub><uuid>70bdb2dd3cf144288a6a00b36399ed79</uuid></formhub>' +
    '<hh>' +
    '<hh>hi</hh>' +
    '</hh>' +
    '<meta><instanceID></instanceID></meta>' +
    '</nodename_bug>' +
    '</instance>' +
    '</model>';

var formStr4 =
    '<form class="or" id="nodename_bug">' +
    '<section class="form-logo"> </section>' +
    '<h2 id="form-title">Node Name bug (issue 169)</h2>' +
    '<fieldset class="question" name="/nodename_bug/hh"><label class="question">' +
    '<span lang="" class="">Enter text</span><input name="/nodename_bug/hh/hh" type="text" data-type-xml="string"/>' +
    '</label></fieldset>' +
    '<fieldset id="or-calculated-items" style="display:none;"><label class="question">' +
    '<input name="/nodename_bug/formhub/uuid" type="hidden" data-calculate="uuid()" data-type-xml="string"/>' +
    '</label></fieldset>' +
    '</form>';

var dataStr5a =
    '<model>' +
    '<instance>' +
    '<widgets id="testPreloads" version="1"  >' +
    '<start_time>2012-10-30T08:44:57.000-06</start_time>' +
    '<end_time>2012-10-30T08:44:57.000-06:00</end_time>' +
    '<date_today>2012-10-30</date_today>' +
    '<deviceid>some value</deviceid>' +
    '<subscriberid>some value</subscriberid>' +
    '<my_simid>2332</my_simid>' +
    '<my_phonenumber>234234324</my_phonenumber>' +
    '<application>some context</application>' +
    '<patient>this one</patient>' +
    '<user>John Doe</user>' +
    '<uid>John Doe</uid>' +
    '<browser_name>fake</browser_name>' +
    '<browser_version>xx</browser_version>' +
    '<os_name>fake</os_name>' +
    '<os_version>xx</os_version>' +
    '<unknown>some value</unknown>' +
    '<meta>' +
    '<instanceID>uuid:56c19c6c-08e6-490f-a783-e7f3db788ba8</instanceID>' +
    '</meta>' +
    '</widgets>' +
    '</instance>' +
    '</model>';

var dataStr5b =
    '<model>' +
    '<instance>' +
    '<widgets id="testPreloads" version="1"  >' +
    '<start_time></start_time>' +
    '<end_time></end_time>' +
    '<date_today></date_today>' +
    '<deviceid></deviceid>' +
    '<subscriberid></subscriberid>' +
    '<my_simid></my_simid>' +
    '<my_phonenumber></my_phonenumber>' +
    '<application></application>' +
    '<patient></patient>' +
    '<user></user>' +
    '<uid></uid>' +
    '<browser_name></browser_name>' +
    '<browser_version></browser_version>' +
    '<os_name></os_name>' +
    '<os_version></os_version>' +
    '<unknown></unknown>' +
    '<meta>' +
    '<instanceID></instanceID>' +
    '</meta>' +
    '</widgets>' +
    '</instance>' +
    '</model>';

var formStr5 =
    '<form class="or" id="testPreloads">' +
    '<section class="form-logo"></section>' +
    '<h2 id="form-title">Test: Preloads JavaRosa</h2>' +
    '<div id="stats" style="display: none;">' +
    '</div>' +
    '<fieldset id="or-preload-items" style="display:none;">' +
    '<label class="question">' +
    '<input name="/widgets/start_time" type="hidden" data-preload="timestamp" data-preload-params="start" data-type-xml="dateTime"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/end_time" type="hidden" data-preload="timestamp" data-preload-params="end" data-type-xml="dateTime"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/date_today" type="hidden" data-preload="date" data-preload-params="today" data-type-xml="date"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/deviceid" type="hidden" data-preload="property" data-preload-params="deviceid" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/subscriberid" type="hidden" data-preload="property" data-preload-params="subscriberid" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/my_simid" type="hidden" data-preload="property" data-preload-params="simserial" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/my_phonenumber" type="hidden" data-preload="property" data-preload-params="phonenumber" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/application" type="hidden" data-preload="context" data-preload-params="application" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/patient" type="hidden" data-preload="patient" data-preload-params="" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/user" type="hidden" data-preload="user" data-preload-params="user_id" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/uid" type="hidden" data-preload="uid" data-preload-params="" data-type-xml="string"/>' +
    '</label>' +
    '<label class="question">' +
    '<input name="/widgets/meta/instanceID" type="hidden" data-preload="instance" data-preload-params="" data-type-xml="string"/>' +
    '</label>' +
    '</fieldset>' +
    '</form>';

var dataStr6 =
    '<model>' +
    '<instance>' +
    '<data id="TestGroupBranch" version="3">' +
    '<nodeA/>' +
    '<group>' +
    '<nodeB/>' +
    '</group>' +
    '<nodeC/>' +
    '</data>' +
    '</instance>' +
    '</model>';

var formStr6 =
    '<form class="or" id="TestGroupBranch">' +
    '<div id="form-languages" style="display:none;" data-default-lang="">' +
    '<a href="#" lang="en">' +
    '<span>English</span>' +
    '</a>' +
    '</div>' +
    '<fieldset class="">' +
    '<label class="question">' +
    '<span lang="en">Enter yes to reveal group</span>' +
    '<input name="/data/nodeA" type="text" data-type-xml="string"/>' +
    '</label>' +
    '</fieldset>' +
    '<fieldset class="or-group or-branch pre-init" name="/data/group" data-relevant="/data/nodeA = &quot;yes&quot;">' +
    '<h4><span lang="en">Group with relevant binding</span></h4>' +
    '<label class="question">' +
    '<span lang="en">Enter 2 to reveal select1</span>' +
    '<input name="/data/group/nodeB" type="number" data-type-xml="int" required="required"/>' +
    '</label>' +
    '</fieldset>' +
    '<label class="question or-branch pre-init or-appearance-minimal">' +
    '<span lang="en">Select 1 option</span>' +
    '<select name="/data/nodeC" data-relevant="/data/group/nodeB = 2">' +
    '<option value="">...</option>' +
    '<option value="r">option 1</option>' +
    '<option value="g">option 2</option>' +
    '<option value="b">option 3</option>' +
    '</select>' +
    '</label>' +
    '</form>';

var dataStr7 =
    '<model>' +
    '<instance>' +
    '<data>' +
    '<nodeA/>' +
    '<nodeB>1</nodeB>' +
    '<group>' +
    '<nodeC/>' +
    '</group>' +
    '</data>' +
    '</instance>' +
    '</model>';

var formStr7 =
    '<form class="or">' +
    '<fieldset class="or-group or-branch pre-init" name="/data/group" data-relevant="/data/nodeA > 0">' +
    '<label class="question or-branch pre-init">' +
    '<span>Enter 2 to reveal select1</span>' +
    '<input name="/data/group/nodeC" type="number" data-type-xml="int" data-relevant="/data/nodeB > 0">' +
    '</label>' +
    '</fieldset>' +
    '</form>';

var dataEditStr_nested_repeats =
    '<nested_repeats id="nested_repeats">' +
    '<formhub>' +
    '<uuid>f19b44ccf710492eb4d1ed6f468324f1</uuid>' +
    '</formhub>' +
    '<kids>' +
    '<has_kids>1</has_kids>' +
    '<kids_details>' +
    '<kids_name>Tom</kids_name>' +
    '<kids_age>2</kids_age>' +
    '<immunization_info>' +
    '<vaccine>Polio</vaccine>' +
    '</immunization_info>' +
    '<immunization_info>' +
    '<vaccine>Rickets</vaccine>' +
    '</immunization_info>' +
    '</kids_details>' +
    '<kids_details>' +
    '<kids_name>Dick</kids_name>' +
    '<kids_age>5</kids_age>' +
    '<immunization_info>' +
    '<vaccine>Malaria</vaccine>' +
    '</immunization_info>' +
    '<immunization_info>' +
    '<vaccine>Flu</vaccine>' +
    '</immunization_info>' +
    '<immunization_info>' +
    '<vaccine>Polio</vaccine>' +
    '</immunization_info>' +
    '</kids_details>' +
    '<nested_group>' +
    '<nested_name>Yo</nested_name>' +
    '<nested_age>25</nested_age>' +
    '</nested_group>' +
    '</kids>' +
    '<gps>-1.2627107 36.7925771 0.0 37.5</gps>' +
    '<web_browsers>firefox chrome safari</web_browsers>' +
    '</nested_repeats>';
